# .readthedocs.yml
# Configuration for Read the Docs (future documentation hosting)

version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"

python:
  install:
    - requirements: requirements.txt
    - requirements: requirements-dev.txt

sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

formats:
  - pdf
  - epub
